### ISSUE TITLE
License in setup.py: Need to replace s/MIT/BSD/

### ISSUE THREAD

**Issue by mbargull** [cmap/cmapPy#30]
The license in `setup.py` (and thus the one displayed at PyPI) is given as `MIT` (or a non-existent 3-clause MIT):
https://github.com/cmap/cmapPy/blob/v3.1.0/setup.py#L28
https://github.com/cmap/cmapPy/blob/v3.1.0/setup.py#L43
I suppose you want those to be `BSD`.

**Comment by oena** [comment]
Thanks, fixed.

**Comment by mbargull** [comment]
That was quick! Thanks.
