### ISSUE TITLE
Bug for the 3.1.1 version

### ISSUE THREAD

**Issue by crotoc** [cmap/cmapPy#35]
Just want to report the bug: this issue only happen for 3.1.1. I stuck for a whole day...
>>> from cmapPy.pandasGEXpress import parse
>>> x=parse("/fs0/chenr6/Database_fs0/LINCS/GSE92742_Broad_LINCS_Level5_COMPZ.MODZ_n473647x12328.gctx",col_meta_only=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable

**Comment by oena** [comment]
Hi @crotoc, sorry to hear that. I've updated the pandasGEXpress tutorial to have the correct syntax for v3.1.1--which should resolve your issue--and also added a check of which cmapPy version is being used in the "Activate your cmapPy conda environment" so there isn't ambiguity in the future. Definitely let us know if you have any more issues!
