### ISSUE TITLE
 No module named cmap.io.gct

### ISSUE THREAD

**Issue by liuguangdi** [cmap/cmapPy#38]
I'm trying to read in a .gctx file in Python and write it as a .gct file. If I follow the instructions in the GitHub readme, I run the following codes:
#!/usr/bin/env python
import sys
import numpy as np
import cmap.io.gct as gct
def main():
    infile = sys.argv[1]
    outfile = sys.argv[2]
    
    gctobj = gct.GCT(infile)
    gctobj.read()
    
    data = gctobj.matrix[:, :].astype('float64')
    
    np.save(outfile, data)
  
if __name__ == '__main__':
    main()

Then, I get the following error:
 No module named cmap.io.gct

**Comment by levlitichev** [comment]
I also have no idea what Github readme you're referring to. `cmap.io.gct` has been deprecated for a long time. Could you post a URL so we can take down outdated instructions?

As @oena suggested, it sounds like the methods you're looking for are under cmapPy/pandasGEXpress.
