### ISSUE TITLE
pandasGEXpress all rid, cid default as strings in HDF5

### ISSUE THREAD

**Issue by dedavison** [cmap/cmapPy#4]
> try these for starters - I think one has them as ints, the other as strings:
> /cmap/projects/GEO_deposition/2017-01/combined_matrices/GSE70138_Broad_LINCS_Level2_GEX_n345976x978.gctx
> /cmap/projects/M1/DATASETS/GEO/matrices/GSE92742_Broad_LINCS_Level3_INF_mlr12k_n1319138x12328.gctx
--DL

**Comment by dllahr** [comment]
fixed in 1bec0f8cb57df6a5b844fe190ddf13cfce9bc000
