### ISSUE TITLE
Parsing GCT files fails in python3

### ISSUE THREAD

**Issue by saksham219** [cmap/cmapPy#53]
I don't know if the code has been made python3 compatible or not. I am providing the example for regenerating this issue in python3. Link to input file [gct file](https://drive.google.com/open?id=1MMevmBB7zSJqcuHvVPvL_HzxPsjzDDiS)

`
from cmapPy.pandasGEXpress.parse import parse
`
`
parse("gct_file_path")
`

 line 168, in read_version_and_dims
    version = f.readline().strip().lstrip("#")
TypeError: a bytes-like object is required, not 'str'

The problem is due to the fact that my GCT file uses bytes string encoding therefore while reading I will have to lstrip(b'#') while apply it on a bytes object. I can fix this perhaps and make the parsing compatible to both byte('bytes' type in python3) and unicode('str' type in python3) strings.

**Comment by oena** [comment]
Hi @saksham219, the package has not been made Python 3 compatible yet; we still recommend using Python 2.7 as described in the [documentation](https://clue.io/cmapPy/index.html). If you'd like to contribute and add that compatibility though, you're more than welcome to!
