### ISSUE TITLE
Problems parsing gctx due to meta_only 

### ISSUE THREAD

**Issue by joaoreis92** [cmap/cmapPy#6]
Hi there.
I'm being unable to parse a .gctx file. 
I think that's because of line 51 in parse.py which calls for parse_gctx.parse with an argument meta_only which is not defined. 
Thanks

**Comment by dllahr** [comment]
Can you send us the exact lines of code you were trying to use and the exact error message you received?

**Comment by oena** [comment]
Also, which version of cmapPy are you using? We're in the process of making some updates including changing the metadata syntax slightly; meta_only is an argument in versions 1.0.9 and prior but not later.

**Comment by joaoreis92** [comment]
I was running the parse_gctx() function and the version has been cloned from github around the time I wrote here. 
I don't recall the error and don't have that version anymore but was something like "local variable 'meta_only' referenced before assignment"

The issue is now solved with the new commit, as the line containing the variable 'meta_only' was removed from the parse_gctx() function of parse_gctx.py file.

**Comment by oena** [comment]
Ok, thanks for the update @joaoreis92. Glad it's no longer a problem!
