### ISSUE TITLE
CMap tutorial IPython notebook doesn't open 

### ISSUE THREAD

**Issue by deniseduma** [cmap/cmapPy#66]
I'm trying to open the notebook in my browser but it doesn't open! 

cmapPy/tutorials/cmapPy_pandasGEXpress_tutorial.ipynb

Can you fix this, please? 

Thanks,
Denise

**Comment by rbf22** [comment]
I can verify this: NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")

**Comment by rbf22** [comment]
I also see this problem:

Notebook validation failed: 'execution_count' is a required property:
{
 "data": {
  "text/html": "<div>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>chd</th>\n    </tr>\n    <tr>\n      <th>cid</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>REP.A001_A375_24H:A03</th>\n    </tr>\n    <tr>\n      <th>REP.A001_A375_24H:A04</th>\n    </tr>\n    <tr>\n      <th>REP.A001_A375_24H:A05</th>\n    </tr>\n    <tr>\n      <th>REP.A001_A375_24H:A06</th>\n    </tr>\n    <tr>\n      <th>REP.A001_A375_24H:A07</th>\n    </tr>\n  </tbody>\n</table>\n</div>"
 },
 "output_type": "execute_result",
 "metadata": {}
}

**Comment by dhamelse** [comment]
I also cannot open the ipynb file.

**Comment by tnat1031** [comment]
Hi all, apologies for the delay in addressing this but I think the issue should be fixed in this commit dbcb3eda538d183efe8cb1441d237115527e5b52. The file should now open successfully in a Jupyter notebook session.
