### ISSUE TITLE
cmapPy breaks with pandas == 0.20 

### ISSUE THREAD

**Issue by oena** [cmap/cmapPy#9]
Pandas 0.20 changed dtypes slightly; causes some unittests to break. Needs fixing to maintain compatibility with newer versions of requirements packages. 

Details on dtype here: https://pandas.pydata.org/pandas-docs/stable/whatsnew.html#uint64-support-improved

**Comment by dllahr** [comment]
This should be addressed with branch / pull request "upgrade_pandas_etc"
